---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  chart:
    spec:
      chart: gitlab
      sourceRef:
        kind: HelmRepository
        name: charts.gitlab.io
        namespace: gitlab
      version: 8.10.3
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: gitlab
  valuesFrom:
    - kind: ConfigMap
      name: gitlab-8.10.3-defaults
  targetNamespace: gitlab
